# theme
# theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme
permalink: pretty

# site settings
title: VR Docs
author: Richard Musil

# plugins
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme

# defaults
defaults:
  - scope:
      path: "**/*.md"
    values:
      hero_height: is-small
      layout: page
      hide_hero: true
  - scope:
      path: "docs/*.md"
    values:
      layout: post
      author: Richard Musil
      menubar: true
      menubar_toc: true
